//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "ingestion"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    pub id: i32,
    pub substance_name: Option<String>,
    pub administration_route: Option<String>,
    pub dosage_unit: Option<String>,
    pub dosage_amount: Option<f32>,
    pub ingestion_date: Option<String>,
    pub subject_id: Option<String>,
    pub stash_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SubstanceName,
    AdministrationRoute,
    DosageUnit,
    DosageAmount,
    IngestionDate,
    SubjectId,
    StashId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Stash,
    Subject,
    Substance,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::SubstanceName => ColumnType::Text.def().null(),
            Self::AdministrationRoute => ColumnType::Text.def().null(),
            Self::DosageUnit => ColumnType::Text.def().null(),
            Self::DosageAmount => ColumnType::Float.def().null(),
            Self::IngestionDate => ColumnType::custom("datetime").def().null(),
            Self::SubjectId => ColumnType::Text.def().null(),
            Self::StashId => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Stash => Entity::belongs_to(super::stash::Entity)
                .from(Column::StashId)
                .to(super::stash::Column::Id)
                .into(),
            Self::Subject => Entity::belongs_to(super::subject::Entity)
                .from(Column::SubjectId)
                .to(super::subject::Column::Id)
                .into(),
            Self::Substance => Entity::belongs_to(super::substance::Entity)
                .from(Column::SubstanceName)
                .to(super::substance::Column::Name)
                .into(),
        }
    }
}

impl Related<super::stash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stash.def()
    }
}

impl Related<super::subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subject.def()
    }
}

impl Related<super::substance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Substance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::stash::Entity")]
    Stash,
    #[sea_orm(entity = "super::subject::Entity")]
    Subject,
    #[sea_orm(entity = "super::substance::Entity")]
    Substance,
}
