//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.4

pub mod prelude;

pub mod account;
pub mod chemical_class;
pub mod effect;
pub mod ingestion;
pub mod psychoactive_class;
pub mod query_root;
pub mod stash;
pub mod subject;
pub mod substance;
pub mod substance_interactions;
pub mod substance_route_of_administration;
pub mod substance_route_of_administration_dosage;
pub mod substance_route_of_administration_phase;
pub mod substance_synonym;
pub mod substance_tolerance;
