//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod account;
pub mod chemical_class;
pub mod effect;
pub mod ingestion;
pub mod psychoactive_class;
pub mod stash;
pub mod subject;
pub mod substance;
pub mod substance_interactions;
pub mod substance_route_of_administration;
pub mod substance_route_of_administration_dosage;
pub mod substance_route_of_administration_phase;
pub mod substance_synonym;
pub mod substance_tolerance;
