//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ingestion")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub substance_name: String,
    pub ingested_at: String,
    pub dosage: String,
    pub route_of_administration: String,
    
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
