//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "phase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub route_of_administration_id: i32,
    pub phase_classification: String,
    pub duration_min: i32,
    pub duration_max: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
