//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "phase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub route_of_administration_id: i32,
    pub classification: String,
    pub duration_min: String,
    pub duration_max: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::route_of_administration::Entity",
        from = "Column::RouteOfAdministrationId",
        to = "super::route_of_administration::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RouteOfAdministration,
}

impl Related<super::route_of_administration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RouteOfAdministration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
