//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::dosage::Entity as Dosage;
pub use super::ingestion::Entity as Ingestion;
pub use super::phase::Entity as Phase;
pub use super::route_of_administration::Entity as RouteOfAdministration;
pub use super::substance::Entity as Substance;
