//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::dosage::Entity as DosageEntity;
pub use super::ingestion::Entity as IngestionEntity;
pub use super::phase::Entity as PhaseEntity;
pub use super::route_of_administration::Entity as RouteOfAdministrationEntity;
pub use super::substance::Entity as SubstanceEntity;
