//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "route_of_administration")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub substance_name: String,
    pub classification: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dosage::Entity")]
    Dosage,
    #[sea_orm(has_many = "super::phase::Entity")]
    Phase,
}

impl Related<super::dosage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dosage.def()
    }
}

impl Related<super::phase::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Phase.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
