//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "substance_tolerance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_name = "substanceId")]
    pub substance_id: String,
    pub mechanism: String,
    pub mechanism_desciption: Option<String>,
    pub onset_mechanism: String,
    pub onset_description: Option<String>,
    pub decline_mechanism: String,
    pub decline_description: Option<String>,
    pub onset_duration: Option<String>,
    pub decline_to_baseline_duration: Option<String>,
    pub decline_to_half_duration: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::substance::Entity",
        from = "Column::SubstanceId",
        to = "super::substance::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Substance,
}

impl Related<super::substance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Substance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
