//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use tabled::Tabled;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Tabled)]
#[sea_orm(table_name = "substance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub common_names: String,
    pub brand_names: String,
    pub substitute_name: String,
    pub chemical_classes: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
