schema    : schema.graphql
documents : '*.op.graphql'
projects:
  default:
    schema: schema.graphql
    documents: '*.op.graphql'
extensions:
  endpoints:
    default:
      url: 'https://api.psychonautwiki.org/graphql'
      headers:
