version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["apps/server/Dockerfile"]

[[analyzers]]
name = "javascript"

[[transformers]]
name = "prettier"