version: "3.7"
services:
  cockroachdb:
    container_name: ${REPOSITORY_NAME}-cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --advertise-addr ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:26257"
      - "8081:8080"
    volumes:
      - "${PWD}/.cache/cockroach:/cockroach/cockroach-data"
    environment:
      - COCKROACH_USER=${DATABASE_USER}
      - COCKROACH_PASSWORD=${DATABASE_PASSWORD}
      - COCKROACH_DATABASE=${DATABASE_NAME}
