version: "3.7"
services:
  cockroachdb:
    container_name: neuroneek-cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --advertise-addr ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:26257"
      - "8080:8080"
    volumes:
      - "${PWD}/.cache/cockroach:/cockroach/cockroach-data"
    environment:
      - COCKROACH_USER=${DATABASE_USER}
      - COCKROACH_PASSWORD=${DATABASE_PASSWORD}
      - COCKROACH_DATABASE=${DATABASE_NAME}
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 0.25
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 512m
