[project]
name = "neuronek"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jakub Olan", email = "keinsell@protonmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
