components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        RegisterUserDTO:
            properties:
                firstName:
                    type: string
                    description: 'The user''s first name'
                    example: John
                lastName:
                    type: string
                    description: 'The user''s last name'
                    example: Doe
                    maxLength: 50
                    minLength: 1
                    pattern: '^[a-zA-Z0-9_]*$'
                email:
                    type: string
                    description: 'Email of user'
                password: {}
                username:
                    type: string
                dateOfBirth:
                    type: string
                    format: date-time
                height:
                    type: number
                    format: double
                weight:
                    type: number
                    format: double
            required:
                - password
                - username
            type: object
            additionalProperties: false
    securitySchemes: {}
info:
    title: Neuronek
    version: 1.0.0
openapi: 3.0.0
paths:
    /user/register:
        post:
            operationId: register-user
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
                            examples:
                                'Example 1':
                                    value: {id: 1, email: "", name: 'John Doe', phoneNumbers: []}
                '201':
                    description: 'Created user successfully'
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                'Example 1':
                                    value: cl864jzha0005ted5rfkcrik3
            security: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterUserDTO'
servers:
    -
        url: /api
yaml: true
