components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas: {}
    securitySchemes: {}
info:
    title: Neuronek
    version: 1.0.0
openapi: 3.0.0
paths:
    /user/register:
        post:
            operationId: register-user
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
                '201':
                    description: 'Created user successfully'
            description: 'Creates new user'
            security: []
            parameters: []
servers:
    -
        url: /api
yaml: true
