# Database Management Front-End

database_management: "-- Database Management --"
initalize_database: "Initalize database: database init"
fresh_database: "Restart database: database fresh"

database_management -> initalize_database
database_management -> fresh_database

migration_management: "-- Migration Management --"

list_migrations: "List migrations: migration list"
generate_migration: "Generate migration: migration generate"
list_pending_migrations: "List pending migrations: migration pending"
apply_migrations: "Apply pending migrations: migration apply"
revert_migrations: "Revert applied migrations: migration revert"
redo_migrations: "Revert and apply migrations: migration redo"

migration_management -> list_migrations
list_migrations -> generate_migration
generate_migration -> list_pending_migrations
list_pending_migrations -> apply_migrations
apply_migrations -> revert_migrations
apply_migrations -> redo_migrations