/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gtPeylTj4qr
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { BellIcon, BoxIcon, BrainIcon, HistoryIcon, LayersIcon, LayoutDashboardIcon, PillIcon } from 'lucide-react';

export function Sidebar() {
  return (
    <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
      <div className="flex h-full max-h-screen flex-col gap-2">
        <div className="flex h-[60px] items-center border-b px-6">
          <Link className="flex items-center gap-2 font-semibold" href="#">
            <BrainIcon className="h-6 w-6" />
            <span className="">Neuronek</span>
          </Link>
          <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
            <BellIcon className="h-4 w-4" />
            <span className="sr-only">Toggle notifications</span>
          </Button>
        </div>
        <div className="flex-1 overflow-auto py-2">
          <nav className="grid items-start px-4 text-sm font-medium">
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="/ingestions"
            >
              <LayoutDashboardIcon className="h-4 w-4" />
              Dashboard
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="/ingestions"
            >
              <HistoryIcon className="h-4 w-4" />
              Ingestions
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="/substances"
            >
              <PillIcon className="h-4 w-4" />
              Substances
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="/substances"
            >
              <LayersIcon className="h-4 w-4" />
              Mixtures
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="/ingestions"
            >
              <BoxIcon className="h-4 w-4" />
              Storage
            </Link>
          </nav>
        </div>
        {/*<div className="mt-auto p-4">*/}
        {/*  <Card>*/}
        {/*    <CardHeader className="pb-4">*/}
        {/*      <CardTitle>Neuronek</CardTitle>*/}
        {/*      <CardDescription>Track your psychedelic experiences and gain insights.</CardDescription>*/}
        {/*    </CardHeader>*/}
        {/*    <CardContent>*/}
        {/*      <Button className="w-full" size="sm">*/}
        {/*        Explore*/}
        {/*      </Button>*/}
        {/*    </CardContent>*/}
        {/*  </Card>*/}
        {/*</div>*/}
      </div>
    </div>
  );
}
