load_psychonautwiki: "Fetch substances from PsychonautWiki"
load_effectindex: "Fetch effectindex.json"
import_effects: "Import effects"
import_substances: "Import substances"
import_routes_of_administration: "Import routes of administration"
import_dosage: "Import dosages"
import_phases: "Import phases"

start:
    load_psychonautwiki
    load_effectindex
    import_effects
    import_substances
    import_routes_of_administration
    import_dosage
    import_phases
end
