name: neuronek
services :
  server      :
    container_name : neuronek-server
    image          : neuronek-server:latest
    build          :
      dockerfile : apps/server/docker/Dockerfile
      context    : ..
    ports          :
      - '${PORT}:3000'
    environment    :
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@cockroachdb:${DATABASE_PORT}/${DATABASE_NAME}
    volumes:
      - database_file:/app/prisma/db

  web:
    container_name : neuronek-web
    image          : neuronek-web:latest
    build          :
      dockerfile : apps/web/Dockerfile
      context    : ..
    ports          :
      - '${PORT}:3000'
    environment    :
      - REACT_APP_SERVER_URL=http://localhost:${PORT}
    depends_on     :
      - server
      
volumes:
    database_file:
      name: neuronek-db
      
