# generated by datamodel-codegen:
#   filename:  effectindex.json
#   timestamp: 2024-06-01T10:52:18+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class Video(BaseModel):
    src: str
    height: str
    width: str


class Link(BaseModel):
    text: str
    href: str


class ModelItem(BaseModel):
    title: str
    softTitle: str
    date: None
    author: List[str]
    publisher: str
    copyright: str
    favicon: str
    description: str
    lang: str
    tags: List[str]
    image: Optional[str] = None
    videos: List[Video]
    links: List[Link]
    text: str
    url: str


class Model(RootModel[List[ModelItem]]):
    root: List[ModelItem]
