//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "substance_interactions")]
pub struct Model
{
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "substanceId", column_type = "Text", nullable)]
    pub substance_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
    #[sea_orm(
        belongs_to = "super::substance::Entity",
        from = "Column::SubstanceId",
        to = "super::substance::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Substance,
}

impl Related<super::substance::Entity> for Entity
{
    fn to() -> RelationDef { Relation::Substance.def() }
}

impl ActiveModelBehavior for ActiveModel {}
