direction: left

iam: {
    label: "Identity and Access Management (IAM)"

    account: "Account"
}

subject_database: {
    label: "Subject"

    subject: "Subject"

    subject -> _.iam.account: (optionally)
}

substance_database: {
    label: "Public Substance Information"

    # Substance
    substance: "Substance"
    route_of_administration: "Route of Administration"
    dosage: "Dosage"
    phase: "Phase"

    route_of_administration -> substance
    dosage -> route_of_administration
    phase -> route_of_administration
}

journal: {
    label: "Journal"

    ingestion: "Ingestion"
    ingestion_phase: "Ingestion Phase"

    ingestion -> _.substance_database.substance
    ingestion -> _.subject_database.subject

    ingestion_phase -> ingestion
}

experience_db: {
    label: "Experience Dataset"

    experience: "Expereince"

    experience -> _.subject_database.subject: {
        label: "may contain"
    }
    experience -> _.journal.ingestion: {
        label: "may contain"
    }
}
