

experience: "Experience"
ingestion: "Ingestion"

dosage: "Dosage"
phase: "Phase"


# Account
account: "Account"

# Subject
subject: "Subject"

subject -> account

substance_database: {
    label: "Substance Database"

    # Substance
    substance: "Substance"
    route_of_administration: "Route of Administration"
    route_of_administration_dosage: "Route of Administration Dosage"
    route_of_administration_phase: "Route of Administration Phase"

    route_of_administration -> substance
    route_of_administration_dosage -> route_of_administration
    route_of_administration_phase -> route_of_administration
}



# Route of Administration


route_of_administration -> substance


# Ingestion
ingestion -> subject
ingestion -> substance
