# Bored tennager cargo hacking ______________________
# Optimalizations made in this file have purpose to
# optimize build times in developer settting on weaker
# hardware.
#
# https://unstablerust.dev/



[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=lld",
    "-Zshare-generics=y",
    "-Ccodegen-units=8",
    "-Csplit-debuginfo=unpacked"
]

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y", "-Csplit-debuginfo=unpacked"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=y"]

[unstable]
codegen-backend = true

[build]
artifact-dir = "out"
rustflags = ["-Zunstable-options"]

[gc.auto]
# The maximum frequency that automatic garbage collection happens.
# Can be "never" to disable automatic-gc, or "always" to run on every command.
frequency = "1 day"
# Anything older than this duration will be deleted in the source cache.
max-src-age = "1 month"
# Anything older than this duration will be deleted in the compressed crate cache.
max-crate-age = "3 months"
# Any index older than this duration will be deleted from the index cache.
max-index-age = "3 months"
# Any git checkout older than this duration will be deleted from the checkout cache.
max-git-co-age = "1 month"
# Any git clone older than this duration will be deleted from the git cache.
max-git-db-age = "3 months"

[alias]
b = "zigbuild -Z unstable-options"
c = "check"
d = "doc"
t = "test"
r = "run"
rm = "remove"

[term]
quiet = true
verbose = false

[profile.dev]
codegen-backend = "cranelift"
debug = 1