brace_style = "AlwaysNextLine"
combine_control_expr = false
control_brace_style = "AlwaysNextLine"
fn_single_line = true
inline_attribute_width = 60
match_arm_leading_pipes = "Always"
imports_granularity = "Item"
use_try_shorthand=true
wrap_comments=true
where_single_line=true
blank_lines_upper_bound=2
condense_wildcard_suffixes=true
format_code_in_doc_comments=true
format_strings=true
