/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aOouyN7ZLcQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function LandingPage() {
	return (
		<div className="flex flex-col min-h-screen">
			<header className="bg-gray-900 text-white py-4 px-6 md:px-8">
				<div className="container mx-auto flex items-center justify-between">
					<Link className="flex items-center gap-2 font-semibold" href="#">
						<PillIcon className="h-6 w-6" />
						<span className="">Neuronek</span>
					</Link>
					<nav className="hidden md:flex items-center gap-4">
						<Button variant="default"><Link href={"/login"}>Get Started</Link></Button>
					</nav>
					<Button className="md:hidden" size="icon" variant="outline">
						<MenuIcon className="h-6 w-6" />
						<span className="sr-only">Toggle navigation</span>
					</Button>
				</div>
			</header>
			<main className="flex-1">
				<section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-20">
					<div className="container mx-auto px-4 md:px-6 lg:px-8">
						<div className="grid md:grid-cols-2 gap-8 items-center">
							<div>
								<h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
									Unlock Your Potential with Neuronek
								</h1>
								<p className="text-gray-600 dark:text-gray-400 mb-6">
									Take control of your substance use and unlock your full potential with Neuronek, the ultimate harm reduction and nootropic tracking app.
								</p>
								<div className="flex gap-4">
									<Button variant="default"><Link href={"/login"}>Get Started</Link></Button>
									{/*<Button variant="outline">Learn More</Button>*/}
								</div>
							</div>
							<div>
								<img
									alt="Neuronek"
									className="rounded-lg"
									height={400}
									src="/placeholder.svg"
									style={{
										aspectRatio: "600/400",
										objectFit: "cover",
									}}
									width={600}
								/>
							</div>
						</div>
					</div>
				</section>
				<section className="py-12 md:py-16 lg:py-20" id="features">
					<div className="container mx-auto px-4 md:px-6 lg:px-8">
						<h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">
							Keep eye on your mental health with Neuronek
						</h2>
						<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<PillIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									Substance intake tracking
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Track your nootropic intake and monitor your progress with our intuitive tracking system.
								</p>
							</div>
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<HistoryIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									In-Depth Analytics and Insights
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Gain valuable insights into your nootropic use and optimize your routine with our advanced analytics tools.
								</p>
							</div>
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<AlarmCheckIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									Customizable Reminders and Notifications
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Stay on top of your nootropic routine with customizable reminders and notifications.
								</p>
							</div>
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<PlusIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									Community Support and Resources
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Connect with a community of like-minded individuals and access a wealth of resources and knowledge.
								</p>
							</div>
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<SearchIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									Advanced Search and Filtering
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Quickly find and analyze your nootropic data with our advanced search and filtering tools.
								</p>
							</div>
							<div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-6">
								<PieChartIcon className="h-8 w-8 mb-4" />
								<h3 className="text-xl font-semibold mb-2">
									Visualize Your Progress
								</h3>
								<p className="text-gray-600 dark:text-gray-400">
									Visualize your progress and track your goals with our interactive charts and graphs.
								</p>
							</div>
						</div>
					</div>
				</section>
				<section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-20" id="about">
					<div className="container mx-auto px-4 md:px-6 lg:px-8">
						<div className="grid md:grid-cols-2 gap-8 items-center">
							<div>
								<img
									alt="About Neuronek"
									className="rounded-lg"
									height={400}
									src="/placeholder.svg"
									style={{
										aspectRatio: "600/400",
										objectFit: "cover",
									}}
									width={600}
								/>
							</div>
							<div>
								<h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-4">
									About Neuronek
								</h2>
								<p className="text-gray-600 dark:text-gray-400 mb-6">
									Neuronek is a comprehensive harm reduction and nootropic tracking app designed to help individuals take control of their substance use and unlock their full potential.
								</p>
								<Button variant="default">Learn More</Button>
							</div>
						</div>
					</div>
				</section>
			</main>
			<footer className="bg-gray-900 text-white py-6 px-4 md:px-6">
				<div className="container mx-auto flex items-center justify-between">
					<p className="text-sm">© 2024 Neuronek. All rights reserved.</p>
					<nav className="flex items-center gap-4">
						<Link className="hover:underline" href="#">
							Privacy
						</Link>
						<Link className="hover:underline" href="#">
							Terms
						</Link>
						<Link className="hover:underline" href="#">
							Support
						</Link>
					</nav>
				</div>
			</footer>
		</div>
	)
}

function AlarmCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="13" r="8" />
      <path d="M5 3 2 6" />
      <path d="m22 6-3-3" />
      <path d="M6.38 18.7 4 21" />
      <path d="M17.64 18.67 20 21" />
      <path d="m9 13 2 2 4-4" />
    </svg>
  )
}


function HistoryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M12 7v5l4 2" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PieChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" />
    </svg>
  )
}


function PillIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z" />
      <path d="m8.5 8.5 7 7" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
