[package]
name = "neuronek-cli"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
structopt = { version = "0.3.26" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
chrono = { version = "0.4.38", features = ["serde"] }
chrono-english = "0.1.7"
xdg = "2.5.2"
uom = "0.36.0"
tabled = "0.15.0"
