// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `account` table.
    ///
    /// (Automatically generated by Diesel.)
    account (id) {
        /// The `id` column of the `account` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `username` column of the `account` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Text,
        /// The `password` column of the `account` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Text,
    }
}

diesel::table! {
    /// Representation of the `chemical_class` table.
    ///
    /// (Automatically generated by Diesel.)
    chemical_class (id) {
        /// The `id` column of the `chemical_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `name` column of the `chemical_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `chemical_class` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `effect` table.
    ///
    /// (Automatically generated by Diesel.)
    effect (id) {
        /// The `id` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `name` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `slug` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        slug -> Text,
        /// The `category` column of the `effect` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        category -> Nullable<Text>,
        /// The `type` column of the `effect` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "type"]
        type_ -> Nullable<Text>,
        /// The `tags` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        tags -> Text,
        /// The `summary` column of the `effect` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        summary -> Nullable<Text>,
        /// The `description` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `parameters` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        parameters -> Text,
        /// The `see_also` column of the `effect` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        see_also -> Text,
        /// The `effectindex` column of the `effect` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        effectindex -> Nullable<Text>,
        /// The `psychonautwiki` column of the `effect` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        psychonautwiki -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `ingestion` table.
    ///
    /// (Automatically generated by Diesel.)
    ingestion (id) {
        /// The `id` column of the `ingestion` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `substance_name` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        substance_name -> Nullable<Text>,
        /// The `administration_route` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        administration_route -> Nullable<Text>,
        /// The `dosage_unit` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dosage_unit -> Nullable<Text>,
        /// The `dosage_amount` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Float>`.
        ///
        /// (Automatically generated by Diesel.)
        dosage_amount -> Nullable<Float>,
        /// The `ingestion_date` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        ingestion_date -> Nullable<Timestamp>,
        /// The `subject_id` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        subject_id -> Nullable<Text>,
        /// The `stash_id` column of the `ingestion` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        stash_id -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `psychoactive_class` table.
    ///
    /// (Automatically generated by Diesel.)
    psychoactive_class (id) {
        /// The `id` column of the `psychoactive_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `name` column of the `psychoactive_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `summary` column of the `psychoactive_class` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        summary -> Nullable<Text>,
        /// The `description` column of the `psychoactive_class` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `substanceId` column of the `psychoactive_class` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        substanceId -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `seaql_migrations` table.
    ///
    /// (Automatically generated by Diesel.)
    seaql_migrations (version) {
        /// The `version` column of the `seaql_migrations` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Text,
        /// The `applied_at` column of the `seaql_migrations` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        applied_at -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `stash` table.
    ///
    /// (Automatically generated by Diesel.)
    stash (id) {
        /// The `id` column of the `stash` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `owner_id` column of the `stash` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Text,
        /// The `substance_id` column of the `stash` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        substance_id -> Text,
        /// The `addedDate` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        addedDate -> Nullable<Timestamp>,
        /// The `expiration` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        expiration -> Nullable<Timestamp>,
        /// The `amount` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        amount -> Nullable<Integer>,
        /// The `price` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Nullable<Text>,
        /// The `vendor` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        vendor -> Nullable<Text>,
        /// The `description` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `purity` column of the `stash` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        purity -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `subject` table.
    ///
    /// (Automatically generated by Diesel.)
    subject (id) {
        /// The `id` column of the `subject` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `firstName` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        firstName -> Nullable<Text>,
        /// The `lastName` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        lastName -> Nullable<Text>,
        /// The `dateOfBirth` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        dateOfBirth -> Nullable<Timestamp>,
        /// The `weight` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        weight -> Nullable<Integer>,
        /// The `height` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        height -> Nullable<Integer>,
        /// The `account_id` column of the `subject` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        account_id -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `substance` table.
    ///
    /// (Automatically generated by Diesel.)
    substance (id) {
        /// The `id` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `name` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `common_names` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        common_names -> Text,
        /// The `brand_names` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        brand_names -> Text,
        /// The `substitutive_name` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        substitutive_name -> Nullable<Text>,
        /// The `systematic_name` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        systematic_name -> Text,
        /// The `pubchem_cid` column of the `substance` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        pubchem_cid -> Integer,
        /// The `unii` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        unii -> Nullable<Text>,
        /// The `cas_number` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        cas_number -> Nullable<Text>,
        /// The `inchi_key` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        inchi_key -> Text,
        /// The `smiles` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        smiles -> Text,
        /// The `psychonautwiki_url` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        psychonautwiki_url -> Nullable<Text>,
        /// The `psychoactive_class` column of the `substance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        psychoactive_class -> Text,
        /// The `chemical_class` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        chemical_class -> Nullable<Text>,
        /// The `description` column of the `substance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `substance_interactions` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_interactions (id) {
        /// The `id` column of the `substance_interactions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `substanceId` column of the `substance_interactions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        substanceId -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `substance_route_of_administration` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_route_of_administration (id) {
        /// The `id` column of the `substance_route_of_administration` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `substanceName` column of the `substance_route_of_administration` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        substanceName -> Text,
        /// The `name` column of the `substance_route_of_administration` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `substance_route_of_administration_dosage` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_route_of_administration_dosage (id) {
        /// The `id` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `intensity` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        intensity -> Text,
        /// The `lower_bound_amount` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Nullable<Float>`.
        ///
        /// (Automatically generated by Diesel.)
        lower_bound_amount -> Nullable<Float>,
        /// The `upper_bound_amount` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Nullable<Float>`.
        ///
        /// (Automatically generated by Diesel.)
        upper_bound_amount -> Nullable<Float>,
        /// The `unit` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        unit -> Text,
        /// The `routeOfAdministrationId` column of the `substance_route_of_administration_dosage` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        routeOfAdministrationId -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `substance_route_of_administration_phase` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_route_of_administration_phase (id) {
        /// The `id` column of the `substance_route_of_administration_phase` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `classification` column of the `substance_route_of_administration_phase` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        classification -> Text,
        /// The `lower_duration` column of the `substance_route_of_administration_phase` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        lower_duration -> Nullable<Text>,
        /// The `upper_duration` column of the `substance_route_of_administration_phase` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        upper_duration -> Nullable<Text>,
        /// The `routeOfAdministrationId` column of the `substance_route_of_administration_phase` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        routeOfAdministrationId -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `substance_route_of_administration_phase_effects` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_route_of_administration_phase_effects (rowid) {
        /// The `rowid` column of the `substance_route_of_administration_phase_effects` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Integer,
        /// The `A` column of the `substance_route_of_administration_phase_effects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        A -> Text,
        /// The `B` column of the `substance_route_of_administration_phase_effects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        B -> Text,
    }
}

diesel::table! {
    /// Representation of the `substance_synonym` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_synonym (id) {
        /// The `id` column of the `substance_synonym` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `substanceId` column of the `substance_synonym` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        substanceId -> Text,
        /// The `name` column of the `substance_synonym` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `substance_tolerance` table.
    ///
    /// (Automatically generated by Diesel.)
    substance_tolerance (id) {
        /// The `id` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `substanceId` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        substanceId -> Text,
        /// The `mechanism` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        mechanism -> Text,
        /// The `mechanism_desciption` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        mechanism_desciption -> Nullable<Text>,
        /// The `onset_mechanism` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        onset_mechanism -> Text,
        /// The `onset_description` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        onset_description -> Nullable<Text>,
        /// The `decline_mechanism` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        decline_mechanism -> Text,
        /// The `decline_description` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        decline_description -> Nullable<Text>,
        /// The `onset_duration` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        onset_duration -> Nullable<Text>,
        /// The `decline_to_baseline_duration` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        decline_to_baseline_duration -> Nullable<Text>,
        /// The `decline_to_half_duration` column of the `substance_tolerance` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        decline_to_half_duration -> Nullable<Text>,
    }
}

diesel::joinable!(ingestion -> stash (stash_id));
diesel::joinable!(ingestion -> subject (subject_id));
diesel::joinable!(psychoactive_class -> substance (substanceId));
diesel::joinable!(stash -> subject (owner_id));
diesel::joinable!(subject -> account (account_id));
diesel::joinable!(substance_interactions -> substance (substanceId));
diesel::joinable!(substance_route_of_administration_dosage -> substance_route_of_administration (routeOfAdministrationId));
diesel::joinable!(substance_route_of_administration_phase -> substance_route_of_administration (routeOfAdministrationId));
diesel::joinable!(substance_route_of_administration_phase_effects -> effect (A));
diesel::joinable!(substance_route_of_administration_phase_effects -> substance_route_of_administration_phase (B));
diesel::joinable!(substance_synonym -> substance (substanceId));
diesel::joinable!(substance_tolerance -> substance (substanceId));

diesel::allow_tables_to_appear_in_same_query!(
    account,
    chemical_class,
    effect,
    ingestion,
    psychoactive_class,
    seaql_migrations,
    stash,
    subject,
    substance,
    substance_interactions,
    substance_route_of_administration,
    substance_route_of_administration_dosage,
    substance_route_of_administration_phase,
    substance_route_of_administration_phase_effects,
    substance_synonym,
    substance_tolerance,
);
