import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: 'Neuronek',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
    <body>
    <main>{children}</main>
    <Toaster />
    </body>
    </html>
  );
}
