cargo-features = ["edition2024"]

[workspace]
members = [
    "db/rust-seaorm-client",
    "apps/cli",
    "apps/rust-server"
, "libs/neuronek-domain"]
resolver = "2"

[profile.dev]
opt-level = 0
debug = "full"

[profile.release]
opt-level = 0
lto = false
codegen-units = 1
panic = "abort"
strip = false
debug = false
