name : CI

on   :
  push         :
    branches : [ trunk ]
  pull_request :
    branches : [ trunk ]

env  :
  GIT_LFS_CACHE_DIR : '${{ github.workspace }}/git-lfs-cache'

jobs :
  build-and-test :
    runs-on : ubuntu-latest
    env     :
      TURBO_TOKEN       : ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM        : ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY : true
    steps   :
      -
        uses : actions/checkout@v3
      -
        uses : pnpm/action-setup@v3
        with :
          version : 8
      -
        name : Setup Node.js environment
        uses : actions/setup-node@v3
        with :
          node-version : latest
          cache        : pnpm
      
      -
        uses : pnpm/action-setup@v3
        name : Install pnpm
        with :
          run_install : false
      
      -
        name  : Get pnpm store directory
        shell : bash
        run   : |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      -
        uses : actions/cache@v4
        name : Setup pnpm cache
        with :
          path         : ${{ env.STORE_PATH }}
          key          : "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys : |
            ${{ runner.os }}-pnpm-store-
      
      -
        name : Install dependencies
        run  : pnpm install --frozen-lockfile --prefer-offline --reporter=ndjson
      
      -
        name : Install pnpm
        run  : npm i -g turbo
      
      -
        name : Build
        run  : pnpm run build
  # TODO: Add Matrix builds? https://github.com/rust-build/rust-build.action
  cli-build:
    name: "[apps/cli] Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: nightly
          SRC_DIR: apps/cli
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.compile.outputs.BUILT_ARCHIVE }}"
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
